---
- name: Create tomcat AWS infrastructure
  hosts: localhost
  connection: local
  roles:
    - tomcat_aws

- name: Deploy tomcat service
  hosts: webservers
  become: yes
  remote_user: ubuntu
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: "install python"
      raw: sudo apt-get -y install python
  environment:
    ANSIBLE_CONFIG: "ansible.cfg"
  roles:
    - tomcat
