---
- name: Create tomcat AWS infrastructure
  hosts: localhost
  connection: local
  roles:
    - tomcat_aws

- name: Deploy tomcat service
  hosts: webservers
  become: yes
  remote_user: ubuntu
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: "install python"
      raw: sudo apt-get -y install python
  environment:
    ANSIBLE_CONFIG: "ansible.cfg"
  roles:
    - tomcat

  tasks:
    - copy:
       src: /var/lib/jenkins/workspace/E2EProject/target/nvnshoppingcart.war
       dest: /usr/local/apache-tomcat-8.0.23/webapps/
       mode: 0777
       owner: root
       group: root
    - name: start tomcat service
      become: true
      service: name=tomcat state=started
